# This is quite nice, I thought I needed web scraping knowledge first to get data like this, but apparently I could just
# get them from https://opentdb.com/api_config.php for a trivia DB! Nice! I can actually play this :)

question_data = [
    {"category": "General Knowledge", "difficulty": "medium",
     "question": "The US emergency hotline is 911 because of the September 11th terrorist attacks.",
     "correct_answer": "F"},
    {"category": "General Knowledge", "difficulty": "medium",
     "question": "The sum of all the numbers on a roulette wheel is 666.", "correct_answer": "T",
     },
    {"category": "General Knowledge", "difficulty": "medium",
     "question": "There are 86400 seconds in a day.", "correct_answer": "T",
     },
    {"category": "General Knowledge", "difficulty": "medium",
     "question": "The word &quot;news&quot; originates from the first letters of the 4 main directions on a compass (North, East, West, South).",
     "correct_answer": "F"},
    {"category": "General Knowledge", "difficulty": "medium",
     "question": "An eggplant is a vegetable.", "correct_answer": "F"},
    {"category": "General Knowledge", "difficulty": "medium",
     "question": "The bikini is named after the &quot;Bikini Atoll&quot;, an island where the United States conducted tests on atomic bombs.",
     "correct_answer": "T"},
    {"category": "General Knowledge", "difficulty": "medium",
     "question": "Kissing someone for one minute burns about 2 calories.", "correct_answer": "T",
     },
    {"category": "General Knowledge", "difficulty": "medium",
     "question": "Sitting for more than three hours a day can cut two years off a person&#039;s life expectancy.",
     "correct_answer": "T"},
    {"category": "General Knowledge", "difficulty": "medium",
     "question": "Albert Einstein had trouble with mathematics when he was in school.", "correct_answer": "F",
     },
    {"category": "General Knowledge", "difficulty": "medium",
     "question": "The commercial UK channel ITV stands for &quot;International Television&quot;.",
     "correct_answer": "F"},
    {"category": "Entertainment: Video Games", "difficulty": "medium",
     "question": "Nintendo started out as a playing card manufacturer.",
     "correct_answer": "T"},
    {"category": "Entertainment: Video Games", "difficulty": "medium",
     "question": "The Ace Attorney trilogy was suppose to end with &quot;Phoenix Wright: Ace Attorney &minus; Trials and Tribulations&quot; as its final game.",
     "correct_answer": "T"},
    {"category": "Entertainment: Video Games", "difficulty": "medium",
     "question": "&quot;Metal Gear Solid 3: Snake Eater&quot; takes place on Shadow Moses Island.",
     "correct_answer": "F"},
    {"category": "Entertainment: Video Games", "difficulty": "medium",
     "question": "Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.",
     "correct_answer": "T"},
    {"category": "Entertainment: Video Games", "difficulty": "medium",
     "question": "In Half-Life 2, if you play the zombies&#039; speech in reverse, they actually speak coherent English.",
     "correct_answer": "T"},
    {"category": "Entertainment: Video Games", "difficulty": "medium",
     "question": "TF2: The Heavy&#039;s voice actor, Gary Schwartz, voices the Demoman as well ",
     "correct_answer": "T"},
    {"category": "Entertainment: Video Games", "difficulty": "medium",
     "question": "In Rocket League, you can play Basketball.", "correct_answer": "T",
     },
    {"category": "Entertainment: Video Games", "difficulty": "medium",
     "question": "In Monster Hunter Generations, guild style is a type of hunting style.",
     "correct_answer": "T"},
    {"category": "Entertainment: Video Games", "difficulty": "medium",
     "question": "The character that would eventually become Dr. Eggman was considered for the role of Sega&#039;s new flagship mascot before Sonic was.",
     "correct_answer": "T"},
    {"category": "Entertainment: Video Games", "difficulty": "medium",
     "question": "In the Season One Championship of &quot;League of Legends&quot;, the highest achievable rank was Diamond.",
     "correct_answer": "F"},
    {"category": "Science: Computers", "difficulty": "medium",
     "question": "The HTML5 standard was published in 2014.", "correct_answer": "T",
     },
    {"category": "Science: Computers", "difficulty": "medium",
     "question": "The first computer bug was formed by faulty wires.",
     "correct_answer": "F"},
    {"category": "Science: Computers", "difficulty": "medium",
     "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
     "correct_answer": "T"},
    {"category": "Science: Computers", "difficulty": "medium",
     "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
     "correct_answer": "F"},
    {"category": "Science: Computers", "difficulty": "medium",
     "question": "&quot;Windows NT&quot; is a monolithic kernel.",
     "correct_answer": "F"},
    {"category": "Science: Computers", "difficulty": "medium",
     "question": "MacOS is based on Linux.", "correct_answer": "F",
     },
    {"category": "Science: Computers", "difficulty": "medium",
     "question": "The first dual-core CPU was the Intel Pentium D.",
     "correct_answer": "F"},
    {"category": "Science: Computers", "difficulty": "medium",
     "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
     "correct_answer": "T"},
    {"category": "Science: Computers", "difficulty": "medium",
     "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
     "correct_answer": "F"},
    {"category": "Science: Computers", "difficulty": "medium",
     "question": "A Boolean value of &quot;0&quot; represents which of these words?",
     "correct_answer": "F"},
    {"category": "Animals", "difficulty": "medium",
     "question": "An octopus can fit through any hole larger than its beak.",
     "correct_answer": "T"},
    {"category": "Animals", "difficulty": "easy",
     "question": "Kangaroos keep food in their pouches next to their children.",
     "correct_answer": "F"},
    {"category": "Animals", "difficulty": "easy",
     "question": "A bear does NOT defecate during hibernation. ",
     "correct_answer": "T"},
    {"category": "Animals", "difficulty": "medium",
     "question": "The average lifespan of a wildcat is only around 5-6 years. ",
     "correct_answer": "F"},
    {"category": "Animals", "difficulty": "easy",
     "question": "Rabbits are carnivores.", "correct_answer": "F",
     },
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "The Neanderthals were a direct ancestor of modern humans.",
     "correct_answer": "F"},
    {"category": "Science & Nature", "difficulty": "easy",
     "question": "Igneous rocks are formed by excessive heat and pressure.",
     "correct_answer": "F"},
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "A person can get sunburned on a cloudy day.",
     "correct_answer": "T"},
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "Hippopotomonstrosesquippedaliophobia is the irrational fear of long words.",
     "correct_answer": "T"},
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "The &quot;Gympie Stinger&quot; is the deadliest plant in the world.",
     "correct_answer": "F"},
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "The planet Mars has two moons orbiting it.",
     "correct_answer": "T"},
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "Steel is an alloy of Iron and Carbon.", "correct_answer": "T",
     },
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "Like with the Neanderthals, Homo sapiens sapiens also interbred with the Denisovans.",
     "correct_answer": "T"},
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "A defibrillator is used to start up a heartbeat once a heart has stopped beating.",
     "correct_answer": "F"},
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "Shrimp can swim backwards.", "correct_answer": "T",
     },
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "Type 1 diabetes is a result of the liver working improperly.",
     "correct_answer": "F"},
    {"category": "Science & Nature", "difficulty": "hard",
     "question": "It was once believed that injecting shark cartilage into people would prevent them from contracting cancer.",
     "correct_answer": "T"},
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "Anatomy considers the forms of macroscopic structures such as organs and organ systems.",
     "correct_answer": "T"},
    {"category": "Science & Nature", "difficulty": "easy",
     "question": "Salt is 100% composed of Sodium.", "correct_answer": "F",
     },
    {"category": "Science & Nature", "difficulty": "easy",
     "question": "An atom contains a nucleus.", "correct_answer": "T",
     },
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "Scientists accidentally killed the once known world&#039;s oldest living creature, a mollusc, known to be aged as 507 years old.",
     "correct_answer": "T"},
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "Centripedal force is an apparent force that acts outward on a body moving around a center, arising from the body&#039;s inertia.",
     "correct_answer": "F"},
    {"category": "Science & Nature", "difficulty": "easy",
     "question": "An exothermic reaction is a chemical reaction that releases energy by radiating electricity.",
     "correct_answer": "F"},
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "In the periodic table, Potassium&#039;s symbol is the letter K.",
     "correct_answer": "T"},
    {"category": "Science & Nature", "difficulty": "easy",
     "question": "An Astronomical Unit is the distance between Earth and the Moon.",
     "correct_answer": "F"},
    {"category": "Science & Nature", "difficulty": "hard",
     "question": "The chemical element Lithium is named after the country of Lithuania.",
     "correct_answer": "F"},
    {"category": "Science & Nature", "difficulty": "easy",
     "question": "An average human can go two weeks without water.",
     "correct_answer": "F"},
    {"category": "Science & Nature", "difficulty": "hard",
     "question": "The value of one Calorie is different than the value of one calorie.",
     "correct_answer": "T"},
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "Pneumonoultramicroscopicsilicovolcanoconiosis is a synonym for the disease known as silicosis.",
     "correct_answer": "T"},
    {"category": "Science & Nature", "difficulty": "easy",
     "question": "Water always boils at 100&deg;C, 212&deg;F, 373.15K, no matter where you are.",
     "correct_answer": "F"},
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "Sound can travel through a vacuum.", "correct_answer": "F",
     },
    {"category": "Science & Nature", "difficulty": "easy",
     "question": "Not including false teeth; A human has two sets of teeth in their lifetime.",
     "correct_answer": "T"},
    {"category": "Science & Nature", "difficulty": "easy",
     "question": "A plant that has a life cycle for more than a year is known as an annual.",
     "correct_answer": "F"},
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "The most frequent subconscious activity repeated by the human body is blinking.",
     "correct_answer": "F"},
    {"category": "Science & Nature", "difficulty": "medium",
     "question": "&quot;Tachycardia&quot; or &quot;Tachyarrhythmia&quot; refers to a resting heart-rate near or over 100 BPM.",
     "correct_answer": "T"}]
